# Generated by Django 4.2 on 2023-10-25 14:36

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import index.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Image', models.ImageField(upload_to=index.models.uploadToOriginImage)),
                ('Slogan', models.TextField(max_length=1000)),
                ('Color', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=16), default=list, size=None)),
                ('Background', models.ImageField(upload_to=index.models.uploadToBackground)),
                ('nSupporter', models.IntegerField(default=0)),
                ('nMessageSentToCandidate', models.IntegerField(default=0)),
                ('qwerty', models.IntegerField(default=0)),
                ('RegisterTime', django_jalali.db.models.jDateTimeField(default=index.models.currentDateTime)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMEI', models.CharField(max_length=20)),
                ('nSupport', models.IntegerField(default=0)),
                ('Candidate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.candidate')),
            ],
        ),
    ]
