# Generated by Django 4.2 on 2023-11-02 13:14

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_apikey_id_remove_candidate_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='Code',
            field=models.IntegerField(default=index.models.ranInt, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Code',
            field=models.IntegerField(default=index.models.ranInt, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='messagetocandidate',
            name='Code',
            field=models.IntegerField(default=index.models.ranInt, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='Code',
            field=models.IntegerField(default=index.models.ranInt, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='Code',
            field=models.IntegerField(default=index.models.ranInt, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='Code',
            field=models.IntegerField(default=index.models.ranInt, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='Code',
            field=models.IntegerField(default=index.models.ranInt, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('Code', models.IntegerField(default=index.models.ranInt, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('Image', models.ImageField(upload_to=index.models.uploadToSponsor)),
                ('Proper', models.CharField(max_length=150)),
                ('RegisterTime', django_jalali.db.models.jDateTimeField(default=index.models.currentDateTime)),
                ('Candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.candidate')),
            ],
        ),
    ]
