# Generated by Django 4.2 on 2023-11-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_remove_messagetocandidate_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='SirName',
            field=models.CharField(default='', max_length=200),
        ),
    ]
