# Generated by Django 4.2 on 2023-11-06 17:15

from django.db import migrations, models
import index.models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_infoapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoApp',
        ),
        migrations.AddField(
            model_name='candidate',
            name='AppFile',
            field=models.FileField(default='', upload_to=index.models.uploadToAppFile),
        ),
        migrations.AddField(
            model_name='candidate',
            name='AppName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='VersionApp',
            field=models.CharField(default='1.0.0', max_length=50),
        ),
    ]
