# Generated by Django 5.0.1 on 2024-02-21 16:22

import django.db.models.deletion
import django_jalali.db.models
import index.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_news_file_post_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('Code', models.IntegerField(default=index.models.ranInt, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Icon', models.ImageField(upload_to=index.models.uploadToSocial)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('Code', models.IntegerField(default=index.models.ranInt, primary_key=True, serialize=False)),
                ('Content', models.CharField(max_length=100)),
                ('RegisterTime', django_jalali.db.models.jDateTimeField(default=index.models.currentDateTime)),
                ('Candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.candidate')),
                ('Social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.social')),
            ],
        ),
    ]
